### PR TITLE
new version release (1.2.0)

### PR DESCRIPTION
**Pull request by DeyaZ88**
new version release (1.2.0)

### CODE REVIEW

**Comment by mohannadsaleh** [comment]
Done

**Comment by KhalidAlomar** [comment]
Thank you. Is it stable for production?

**Comment by mohannadsaleh** [comment]
yes khalid , please feel free to share your feedback if you have any .

**Comment by mohannadsaleh** [comment]
its highly recommended to test on test environment before moving to production .

**Comment by KhalidAlomar** [comment]
Great thanks. Here is my feedback: 
- SADAD description shows up in English, I would like to be able to edit that to Arabic or custom text like the one in Credit Card.
- The name of payment method to be editable or translatable to Arabic. Right now it shows in English. Even if chosen language in Admin panel is Arabic. 

Thank you.

**Comment by mohannadsaleh** [comment]
Thank you for the feedback , we will consider it in our next release/enhancements push

**Pull request merged**
